version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build docker image and push to docker hub"
          command: |
            cp Dockerfile.production Dockerfile
            docker build -t darkpsart/example-nodejs-express:latest .
            docker push darkpsart/example-nodejs-express:latest
      - run:
          name: "Call to rancher to deploy"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="CB09DAA811D78E9ACFB9" \
              -e CATTLE_SECRET_KEY="69eBUzS6GRK4huZHkc4PP46D4jusetJqKJseBTBw" \
              -e CATTLE_URL="http://139.5.145.167:8080" \
              etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODE_JS \
              --imageUuid 'docker:darkpsart/example-nodejs-express:latest' \
              -- batch_size 3 --start_first \
              --auto_complete --timeout 600 \
              /
      - run: echo Done
